### ISSUE TITLE
Update all major dependencies

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book-directory-fe#229]
- [x] Update to Vue3. Can use https://www.vuemastery.com/blog/vue-3-migration-build/
We were previously blocked from updating to Vue3 for this project because Algolia Instant Search did not support it. See https://github.com/algolia/vue-instantsearch/issues/890. Algolia Instant search should support Vue3: https://github.com/algolia/vue-instantsearch/issues/890#issuecomment-889265431. Sentry did not fully support it. See https://github.com/getsentry/sentry-javascript/issues/2925. Sentry should support Vue3: https://github.com/getsentry/sentry-javascript/issues/2925#issuecomment-884735745. 
These blockers have been removed, so we should update this project to Vue3. See https://v3.vuejs.org/guide/migration/introduction.html

- [x] Update other dependencies (tailwind, sentry, etc.)

**Comment by SteelWagstaff** [comment]
Sentry should support Vue3: https://github.com/getsentry/sentry-javascript/issues/2925#issuecomment-884735745
Algolia Instant search should support Vue3: https://github.com/algolia/vue-instantsearch/issues/890#issuecomment-889265431

**Comment by arzola** [comment]
I have this PR https://github.com/pressbooks/pressbooks-book-directory-fe/pull/512 but needs some fixes before gets merged

**Comment by SteelWagstaff** [comment]
#512 was merged, but deploy pipeline failed :cry:. Need to figure out why deploy pipeline failed so we can testing in dev & staging environments.

**Comment by SteelWagstaff** [comment]
@SevenSidedSquare We have deployed a 'new' version of the Directory to https://staging.pressbooks.directory. Are you willing/able to run it through the paces and document anything that appears different/broken on this version that works/behaves differently on https://pressbooks.directory? This would include things like applying filters, changing sort order, conducting search, taking a tour, etc.

**Comment by SevenSidedSquare** [comment]
Most things appear the same. I see there are only 55 books in the staging Directory, which limits my ability to test filters. The "Last updated" filter appears to be misbehaving, but that's the only issue I can see. Feature tour, search, browsing, sorting, and other filters appear to be working fine.

**Comment by SteelWagstaff** [comment]
Strange. I see nearly 4000 book. Are you sure you don’t have an uncleared search applied? The last updated filter is one we caught and Oscar is working on fixing. See #522

**Comment by SevenSidedSquare** [comment]
We've stumbled upon something. I had cleared all filters and search queries but was seeing only 55 books in total. Even after I clicked on the collections book covers (which automatically clear filters and search queries) no books showed up.

I've just replicated the issue by doing a search for "things" which produces 55 results. If I then click on one of the collections covers, I see no results (even though the search query is successfully cleared). If I then clear all filters and queries, I see only 55 books again.

The same thing happens if I search for "psychology," except I get 140 results. If I then click a collections book cover, I get no results. Then after clearing the collections filter, I'm back to 140 results, even though no search query is entered.

For some reason, the search query is persistent even after it is cleared by selecting a collection. I have not been able to replicate the issue without clicking one of the collections book covers.

**Comment by SteelWagstaff** [comment]
What happens if you empty out the search field and click the search button again?

**Comment by SevenSidedSquare** [comment]
It does nothing if the search field is empty. The results still display 55 books. There's no way to actually clear the search query except to type something into the search field and then click the search button.

**Comment by SteelWagstaff** [comment]
Filed #523
