### ISSUE TITLE
If book descriptions include hyperlinks, display them in Directory

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-book-directory-fe#410]
As a user of the Directory, I would like to see any links included in the original book description, particularly if those links point to relevant resources related to the book itself.

**Description:** The long and short description for a book may include anchor tags with links in them. These anchor tags are exposed by our book API, grabbed by our fetcher and included in the Algolia index for a given book record. See https://pressbooks.directory/?net=Atlantic%20Canada%20Pressbooks%20Network&q=Building%20Relationships%20With%20Business%20Communication for example. Here's the corresponding Algolia record, complete with an assortment of HTML tags, including anchor elements:
![Screenshot from 2021-09-21 13-56-07](https://user-images.githubusercontent.com/13485451/134246440-10e19641-f3d4-4783-a108-2f2f2c7cb2b4.png)

Before displaying the short/long description in the Directory front end we strip all HTML tags from the item description: https://github.com/pressbooks/pressbooks-book-directory-fe/blob/ab36a81dbd7950d913662ad4c86817f84a715450/src/components/books/Books.vue#L68-L73

We should print and display anchor elements/links in the item.description in the front end of the directory. These links should be styled to resemble other in-text links in the Directory.

**Comment by richard015ar** [comment]
I took a look at this. 
I changed the regex here: https://github.com/pressbooks/pressbooks-book-directory-fe/blob/99670c653e040d3ea4437d7b5294aeb59d0d8ba7/src/components/books/PbBooks.vue#L66, to accept `a` tags, and it works, descriptions show only link tags. Nevertheless, in order to render it, we should use something like `<div v-tml="item.description" />` instead of `{{item.description}}` as we do in [the book card](https://github.com/pressbooks/pressbooks-book-directory-fe/blob/99670c653e040d3ea4437d7b5294aeb59d0d8ba7/src/components/books/BookDetails.vue#L57).
Unfortunately, our custom [VueClamp](https://github.com/pressbooks/pressbooks-book-directory-fe/blob/99670c653e040d3ea4437d7b5294aeb59d0d8ba7/src/components/VueClamp.vue#L1) component responsible for clamp the description text does not work with `v-html`.  We could add a new prop like `html=true` in the component, and handle the text differently when it is an HTML we want to render. It seems more complicated since we build the component through `h()` method, I'd need to investigate it further.

**Comment by richard015ar** [comment]
I did it thanks to ChatGPT who helped me to understand the component and suggested the necessary changes. The next step is to confirm the style applied with Steel and create e2e tests.

Progress available in https://github.com/pressbooks/pressbooks-book-directory-fe/tree/feat/display-links-descriptions

**Comment by richard015ar** [comment]
Draft PR in https://github.com/pressbooks/pressbooks-book-directory-fe/pull/863

**Comment by SteelWagstaff** [comment]
Works as expected in dev and staging directories. Ready for release.
